### ISSUE TITLE
Nuget Error

### ISSUE THREAD

**Issue by Grazty** [JaydenMaalouf/FNAPI#2]
its says this
"Could not install package 'FNAPI 0.0.8'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

**Comment by JaydenMaalouf** [comment]
Ah, this is due to the API being written in .NET Core. You're welcome to compile it on .NET Framework if you'd like though!

**Comment by Wraiyth** [comment]
@JaydenMaalouf Re-target the library to netstandard2.0 which will allow .NET 4.6.1 developers to use it

**Comment by JaydenMaalouf** [comment]
API has been re-targeted in the new NuGet Package - 1.1.0
